routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::group(['middleware' => 'guest'], function() {
    Route::get('/', [App\Http\Controllers\BlogController::class, 'guest'])->name('guest');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('blogs', App\Http\Controllers\BlogController::class);
    Route::get('blogs/{blogId}/upload', [App\Http\Controllers\BlogImageController::class, 'index']);
    Route::post('blogs/{blogId}/upload', [App\Http\Controllers\BlogImageController::class, 'store']);
    Route::get('blog-image/{blogImageId}/delete', [App\Http\Controllers\BlogImageController::class, 'destroy']);

});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $table = 'blogs';

    protected $fillable = [
	'title',
	'slug',
	'description'
    ];
   
    public function images() {
	return $this->hasMany(related: "App\Models\BlogImage"); 
    }
}

app/Models/BlogImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BlogImage extends Model
{
    use HasFactory;

    protected $table = 'blog_images';

    protected $fillable = [  'blog_id', 'image'  ];

    public function blog() {
        return $this->belongsTo(related:'App\Models\Blog');
    }

}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\View\View;
use App\Models\Blog;
use App\Models\BlogImage;

class BlogController extends Controller
{
    public function guest()
    {
//        $blogs =  Blog::all();
	$blogs = Blog::orderBy('created_at','desc')->get();
        $blogImgs = BlogImage::all();
        return view('guest', compact("blogs","blogImgs" ));
    }

    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $blogs = Blog::latest()->paginate(5);
	return view('blogs.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('blogs.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
	    'title' => 'required|string|max:255',
	    'description' => 'required|string|max:255',
	]);
	
	Blog::create($request->all());
	return redirect()->route('blogs.index')->with('success', 'Blog created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(Blog $blog): View
    {
        return view('blogs.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Blog $blog): View
    {
        return view('blogs.edit', compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Blog $blog): RedirectResponse
    {
        $request->validate([
	    'title' => 'required|string|max:255',
	    'description' => 'required|string|max:255',
	]);
	
	$blog->update($request->all());
	return redirect()->route('blogs.index')->with('success', 'Blog updated successfully');
        
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id): RedirectResponse
    {
        $blog->delete();
	return redirect()->route('blogs.index')->with('success', 'Blog deleted successfully');
    }
}

app/Http/Controllers/BlogImageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\BlogImage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;


class BlogImageController extends Controller
{
    public function index(int $blogId) {
	$blog = Blog::findOrFail($blogId);
	$blogImages = BlogImage::where('blog_id', $blogId)->get();
	return view('blog-images.index', compact('blog', 'blogImages'));
    }

    public function store(Request $request, int $blogId) {
	$request->validate([
	    'images.*' => 'required|image|mimes:png,jpg,jpeg,webp'
	]);

	$blog = Blog::findOrFail($blogId);

	$imageData = [];
	if($files = $request->file('images')) {
	    foreach($files as $key => $file) {
		$extension = $file->getClientOriginalExtension();
		$filename = $key.'_'.time().'.'.$extension;

		$path = "uploads/blogs/";
		$file->move($path, $filename);

		$imageData[] = [
		    'blog_id' => $blog->id,
		    'image' => $path.$filename,
		];
	    }
	}

	BlogImage::insert($imageData);
	return redirect()->back()->with('status', 'Upload successfully');
    }

    public function destroy(int $blogImageId) {
	$blogImage = BlogImage::findOrFail($blogImageId);
	//$blogImg = $blogImage->image
	if(File::exists($blogImage->image)) {
	    File::delete($blogImage->image);
	}
	$blogImage->delete();

	return redirect()->back()->with('status', 'Image Deleted');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Blog;
use App\Models\BlogImage;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
	$blogs =  Blog::orderBy('created_at','desc')->get();
	$blogImgs = BlogImage::all();
        return view('home', compact("blogs","blogImgs" ));
    }
    
}

resources/views/blog-images/index.blade.php
@extends('layouts.app')

@section('content')
                <!-- Your edit & delete button comes here.-->

<div class="container mt-5">
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h4>Upload Blog Images
                        <a href="{{ url('blogs') }}" class="btn btn-primary float-end">Back</a>
                    </h4>
                </div>
                <div class="card-body">

                    @if (session('status'))
                        <div class="alert alert-success">{{session('status')}}</div>
	    @endif

                    <h5>Blog Name: {{ $blog->title }}</h5>
                    <hr>

                    @if ($errors->any())
                    <ul class="alert alert-warning">
                        @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                    @endif

                    <form action="{{ url('blogs/'.$blog->id.'/upload') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="mb-3">
                            <label>Upload Images (Max:20 images only)</label>
                            <input type="file" name="images[]" multiple class="form-control" />
                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>

        <div class="col-md-12 mt-4">
            @foreach ($blogImages as $blogImg)
                <img src="{{ asset($blogImg->image) }}" class="border p-2 m-3" style="width: 100px; height: 100px;" alt="Img" />
                <a href="{{ url('blog-image/'.$blogImg->id.'/delete') }}" >Delete</a>
            @endforeach
        </div>
    <div>
</div>
@endsection

resources/views/blogs/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">
            <h2>
                Add Blog 
                <a class="btn btn-danger float-end" href="{{ route('blogs.index') }}"> Back</a>
            </h2>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('blogs.store') }}" method="POST">
                @csrf

                 <div class="row">
                    <div class="col-md-12 col-12">
                        <div class="mb-3">
                            <label>Title</label>
                            <input type="text" name="title" class="form-control" placeholder="Title" />
                        </div>
                    </div>
                    <div class="col-md-12 col-12">
                        <div class="mb-3">
                            <label>Description</label>
                            <textarea class="form-control" name="description" rows="3" placeholder="Enter Description"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 col-12 text-center">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>

            </form>

        </div>
    </div>

@endsection

resources/views/blogs/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">
            <h2>
                Edit Blog
                <a class="btn btn-danger float-end" href="{{ route('blogs.index') }}"> Back</a>
            </h2>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('blogs.update',$blog->id) }}" method="POST">
                @csrf
                @method('PUT')

                 <div class="row">
                    <div class="col-md-12 col-12">
                        <div class="mb-3">
                            <label>Title</label>
                            <input type="text" name="title" class="form-control" value="{{ $blog->title }}" placeholder="Title" />
                        </div>
                    </div>
                    <div class="col-md-12 col-12">
                        <div class="mb-3">
                            <label>Description</label>
                            <textarea class="form-control" name="description" rows="3" placeholder="Enter Description">{{ $blog->description }}</textarea>
                        </div>
                    </div>
                    <div class="col-md-12 col-12 text-center">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>

            </form>

        </div>
    </div>

@endsection

resources/views/blogs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2>
                Laravel Blog from scratch
                <a class="btn btn-primary float-end" href="{{ route('blogs.create') }}"> Create New Blog</a>
            </h2>
        </div>
        <div class="card-body">

            @if (session('success'))
            <div class="alert alert-success">{{ session('success') }}</div>
            @endif

            <table class="table table-bordered">
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th width="280px">Action</th>
                </tr>
                @foreach ($blogs as $blog)
                <tr>
                    <td>{{ $blog->id }}</td>
                    <td>{{ $blog->title }}</td>
                    <td>{{ $blog->description }}</td>
		    <td>
		        <a href="{{ url('blogs/'.$blog->id.'/upload') }}" class="btn btn-info">Add / View Images</a>
           	    </td>
                    <td>
                        <a class="btn btn-info" href="{{ route('blogs.show',$blog->id) }}">Show</a>
                        <a class="btn btn-primary" href="{{ route('blogs.edit',$blog->id) }}">Edit</a>
                        <form action="{{ route('blogs.destroy',$blog->id) }}" method="POST" class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </table>

            {!! $blogs->links() !!}

        </div>
    </div>
@endsection

resources/views/blogs/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">
            <h2>
                Show Blog
                <a class="btn btn-danger float-end" href="{{ route('blogs.index') }}"> Back</a>
            </h2>
        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-md-12 col-12">
                    <div class="mb-3">
                        <label>Title</label>
                        <p>{{ $blog->title }}</p>
                    </div>
                </div>
                <div class="col-md-12 col-12">
                    <div class="mb-3">
                        <label>Description</label>
                        <p>{{ $blog->description }}</p>
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/guest.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <!--@if (Route::has('login'))
    <div class="sm:fixed sm:top-0 sm:right-0 p-6 text-right z-10">
	@auth
	    <a href="{{ url('/home') }}" class="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">Home</a>
    @else
    	<a href="{{ route('login') }}" class="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">Log in</a>
    	@if (Route::has('register'))
 	    <a href="{{ route('register') }}" class="ml-4 font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">Register</a>
	@endif
	@endauth
    </div>
    @endif-->
    <!--div class="row justify-content-center">
        <div class="col-md-10"-->

	    @foreach($blogs as $blog)
	    <div class="card px-2 my-3 py-2">
		<h2 class="card-title">{{ $blog->title }}</h2>
		<h6 class="card-subtitle text-muted">ID: {{ $blog->id }}</h6>
		<p>{{ $blog->description }}</p>
		<div class="row row-cols-3">
		@foreach($blogImgs as $blogImg)
		    @if($blogImg->blog_id == $blog->id)
			    <div class="col">
				<a href="{{ asset($blogImg->image) }}" >
				    <img src="{{ asset($blogImg->image) }}" class="border p-2 m-3" style="width: 200px; height: 200px;">
				</a>
			   </div>
		    @endif
		@endforeach 
		</div>
   	    </div>
	    @endforeach
        </div>
    <!--/div>
</div-->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>

	    @foreach($blogs as $blog)
	    <div class="card px-2 my-3 py-2">
		<h2 class="card-title">{{ $blog->title }}</h2>
		<h6 class="card-subtitle text-muted">ID: {{ $blog->id }}</h6>
		<p>{{ $blog->description }}</p>
		<div class="row row-cols-3">
		@foreach($blogImgs as $blogImg)
		    @if($blogImg->blog_id == $blog->id)
			    <div class="col">
				<a href="{{ asset($blogImg->image) }}" >
				    <img src="{{ asset($blogImg->image) }}" class="border p-2 m-1" style="width: 200px; height: 200px;">
				</a>
			    </div>
		    @endif
		@endforeach 
		</div>
   	    </div>
	    @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light shadow-sm" style="background-color: #e3fdf1;">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('blogs.index') }}">{{ __('Blog') }}</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
	    <div class="d-flex justify-content-center">
		<div class="col-10">
	        @yield('content')
		</div>
	    </div>
        </main>
    </div>
</body>
</html>